<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <RootNamespace>ServiceDeckManagement.Launcher</RootNamespace>
    <VersionSuffix>beta.2</VersionSuffix>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServiceDeckManagement.Contracts\ServiceDeckManagement.Contracts.csproj" />
    <ProjectReference Include="..\ServiceDeckManagement.Infrastructure\ServiceDeckManagement.Infrastructure.csproj" />
  </ItemGroup>
</Project>
