<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <RootNamespace>ServiceDeckManagement.Setup</RootNamespace>
    <VersionSuffix>beta.4</VersionSuffix>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServiceDeckManagement.Domain\ServiceDeckManagement.Domain.csproj" />
    <ProjectReference Include="..\ServiceDeckManagement.Infrastructure\ServiceDeckManagement.Infrastructure.csproj" />
  </ItemGroup>
</Project>
